add_definitions(-D_FILE_OFFSET_BITS=64)
add_definitions(-DPCRE2_CODE_UNIT_WIDTH=16)
add_definitions(-DHAVE_CONFIG_H)
if (WIN32)
    add_definitions(-DOS_WIN)
    add_definitions(-DPTW32_BUILD)
    add_definitions(-DPCRE2_STATIC)
    add_definitions(-D__func__=__FUNCTION__)
    add_definitions(-DR_OK=4)
    add_definitions(-Datoll=_atoi64)
    add_definitions(-Dalloca=_alloca)
    add_definitions(-Dinline=__inline)
else ()
    add_definitions(-DHAVE_DRAND48)
endif ()
